// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh8Q_g1u7hCBVz_KVk1Lgkfzsb-HNydQM',
    appId: '1:76592389155:web:cf5ebc21785d5552a62596',
    messagingSenderId: '76592389155',
    projectId: 'pilltimebackend',
    authDomain: 'pilltimebackend.firebaseapp.com',
    storageBucket: 'pilltimebackend.firebasestorage.app',
    measurementId: 'G-HZSYDQD453',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeokd-5Td32YQVTZKyXd6JKTi9MYkZJjg',
    appId: '1:76592389155:android:d8138b3afb94ae9ba62596',
    messagingSenderId: '76592389155',
    projectId: 'pilltimebackend',
    storageBucket: 'pilltimebackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApgPcN7yqwjf0_ZN8HBVTnGsh7u0anWGY',
    appId: '1:76592389155:ios:ef6c8dc5328f88cea62596',
    messagingSenderId: '76592389155',
    projectId: 'pilltimebackend',
    storageBucket: 'pilltimebackend.firebasestorage.app',
    iosBundleId: 'com.example.pilltime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApgPcN7yqwjf0_ZN8HBVTnGsh7u0anWGY',
    appId: '1:76592389155:ios:ef6c8dc5328f88cea62596',
    messagingSenderId: '76592389155',
    projectId: 'pilltimebackend',
    storageBucket: 'pilltimebackend.firebasestorage.app',
    iosBundleId: 'com.example.pilltime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh8Q_g1u7hCBVz_KVk1Lgkfzsb-HNydQM',
    appId: '1:76592389155:web:c52018c81ac975aea62596',
    messagingSenderId: '76592389155',
    projectId: 'pilltimebackend',
    authDomain: 'pilltimebackend.firebaseapp.com',
    storageBucket: 'pilltimebackend.firebasestorage.app',
    measurementId: 'G-7M5KX7E03Q',
  );

}